# Generated by Django 5.2.3 on 2025-10-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sphere', '0004_paymentverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentverification',
            name='user',
        ),
        migrations.AddField(
            model_name='paymentverification',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentverification',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
