# Generated by Django 5.2.3 on 2025-10-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sphere', '0005_remove_paymentverification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
